### ISSUE TITLE
Update to draft-06?

### ISSUE THREAD

**Issue by armandzwan** [kylef/JSONSchema.swift#24]
Any idea if this will be updated to draft-06?

**Comment by appdog** [comment]
+ 1 for draft-06 update

Link to JSON Schema Draft 6 migration FAQ:
http://json-schema.org/draft-06/json-schema-migration-faq.html

**Comment by handrews** [comment]
draft-07 has now been out for a while (it is backwards-compatible with draft-06)

http://json-schema.org/draft-07/json-schema-release-notes.html

Note that we are reorganizing json-schema.org's implementations page to feature projects that support draft-06 or newer more prominently.

**Comment by NikhilManapure** [comment]
Does anyone know of any other library (or any fork of this one) which supports draft 6/7 ?
@handrews 
@appdog 
@armandzwan 
@kylef 
@amorde

**Comment by armandzwan** [comment]
Maybe it can be done with Codable?

**Comment by handrews** [comment]
@NikhilManapure there are [plenty of implementations](http://json-schema.org/implementations.html) supporting those drafts, although I'm not aware of any Swift implementations of any draft other than this one.

Note that the next draft, which is pretty significant but hopefully essentially feature-complete so we can move to a final spec, comes out next month (the PRs are all done, just waiting for reviews but everyone's on vacation right now).  It will be called `draft/2019-09` rather than `draft-08` because IETF/meta-schema mismatches between the `draft-NN` numbers got too confusing).

There are [work-in-progress review copies](http://json-schema.org/work-in-progress) of the new draft posted, and a [few additional PRs with significant changes](https://github.com/json-schema-org/json-schema-spec/pulls) still being reviewed.

**Comment by kylef** [comment]
Master now contains partial support for JSON Schema Draft 6, 7 and 2019-09, most backwards-compatible changes are now supported excluding if-then-else. The most notable backwards incompatible changes that are currently unsupported is `exclusiveMinimum` and `exclusiveMaximum`.

**Comment by NikhilManapure** [comment]
Thanks a bunch @kylef  @handrews

**Comment by kylef** [comment]
02b799a adds draft-6 and draft-7 specific validators, usage (for now) as follows:

```swift
import JSONSchema

let validator = Draft7Validator(schema: ["type": "string"])
validator.validate(instance: "hello world")
```

Draft7Validator is pretty much compatible with with 2019-08, support in the library will be finalise once 2019-09 is released.

**Comment by NikhilManapure** [comment]
@handrews I believe @kylef 's work should get listed in the list of implementations. He has done an awesome job here.

**Comment by handrews** [comment]
@kylef @NikhilManapure could you update your readme to explain exactly what is and is not supported?  If so I will update the JSON Schema site accordingly.

**Comment by kylef** [comment]
@handrews the README was updated in fc95914bb54d92148c0d0037676001a1ec0749de.

https://github.com/kylef/JSONSchema.swift/releases/tag/0.5.0 contains Draft 4, 6 and 7 support. draft/2019-09 will be "officially" supported in this library upon release.
